spring.application.name=abcbank
spring.datasource.url=jdbc:postgresql://db:5432/example
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
